<h1><?php echo $this->__('Brands List'); ?></h1>

<?php $brandCollection = $this->getBrandCollection(); ?>
<?php if ($brandCollection->count() > 0): ?>

    <ul>
        <?php foreach ($brandCollection as $_brand): ?>
            <li>
                <a href="<?php echo $this->helper('test_brands/brand')->getBrandUrl($_brand); ?>" title="<?php echo $this->escapeHtml($_brand->getName()); ?>">
                    <img src="<?php echo '/media' . DS .$_brand->getImage() ?>" height="50px">
                    <?php echo $_brand->getName(); ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>

<?php else: ?>

    <?php echo $this->__('There are no brands to display.'); ?>

<?php endif; ?>